version: '3'
services:
  web:
    build:
      context: docker/web
      args:
        - "APIKEY=${APIKEY}"
    ports:
      - "${WEB_PORT}:8080"
  gw:
    build: ../..
    ports:
      - "${GW_UDP_PORT_RANGE}:${GW_UDP_PORT_RANGE}/udp"
      - "${GW_PORT}:${GW_PORT}"
  camera:
    build: .
    volumes:
      - .:/go/src/github.com/bookun/skyway-webrtc-gateway/samples/golang
    environment:
      - "APIKEY=${APIKEY}"
      - "DOMAIN=http://gw"
      - "PORT=${GW_PORT}"
    tty: true
